name: mul_sent
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py36h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - dataclasses=0.7=py36_0
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py36hff7bd54_0
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openssl=1.1.1j=h27cfd23_0
  - pillow=8.1.0=py36he98fc37_0
  - python=3.6.10=h7579374_2
  - pytorch=1.7.1=py3.6_cuda10.2.89_cudnn7.6.5_0
  - readline=8.1=h27cfd23_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.8.2=py36_cu102
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - aiocontextvars==0.2.2
    - albumentations==0.4.6
    - astroid==2.4.2
    - backcall==0.2.0
    - beautifulsoup4==4.9.1
    - blis==0.4.1
    - blurhash==1.1.4
    - boost==0.1
    - boto==2.49.0
    - boto3==1.14.57
    - botocore==1.17.57
    - bottleneck==1.3.2
    - bs4==0.0.1
    - catalogue==1.0.0
    - cffi==1.14.5
    - click==7.1.2
    - clip==1.0
    - colorama==0.4.3
    - contextvars==2.4
    - cvxopt==1.2.5
    - cycler==0.10.0
    - cymem==2.0.3
    - cython==0.29.21
    - decorator==4.4.2
    - docutils==0.15.2
    - einops==0.2.0
    - ekphrasis==0.5.1
    - emoji==0.6.0
    - face-detection==0.1.4
    - fairseq==0.9.0
    - fastai==1.0.61
    - fastbpe==0.1.0
    - fastprogress==0.2.5
    - filelock==3.0.12
    - ftfy==5.8
    - future==0.18.2
    - fvcore==0.1.1.post20200716
    - gensim==3.8.3
    - imageio==2.9.0
    - imgaug==0.4.0
    - immutables==0.14
    - importlib-metadata==1.7.0
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - isort==4.3.21
    - jedi==0.17.2
    - jmespath==0.10.0
    - joblib==0.16.0
    - jsonlines==1.2.0
    - kiwisolver==1.2.0
    - language-check==1.1
    - lazy-object-proxy==1.4.3
    - lmdb==0.98
    - loguru==0.5.1
    - lvis==0.5.3
    - lxml==4.5.2
    - mastodon-py==1.5.1
    - matplotlib==3.3.2
    - mccabe==0.6.1
    - metric-learn==0.6.2
    - mklpy==0.5.2
    - munch==2.5.0
    - murmurhash==1.0.2
    - mypy-extensions==0.4.3
    - networkx==2.4
    - nlpaug==0.0.20
    - nltk==3.5
    - numexpr==2.7.1
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencv-python==4.3.0.36
    - packaging==20.4
    - pandas==1.0.5
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pip==20.2.3
    - plac==1.1.3
    - portalocker==1.7.1
    - preshed==3.0.2
    - pretrainedmodels==0.7.4
    - prompt-toolkit==3.0.7
    - protobuf==3.12.4
    - ptyprocess==0.6.0
    - pycontractions==2.0.1
    - pycparser==2.20
    - pyemd==0.5.1
    - pygments==2.7.1
    - pylint==2.5.3
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - python-magic==0.4.18
    - pytumblr==0.1.0
    - pytz==2020.1
    - pywavelets==1.1.1
    - pyyaml==5.3.1
    - regex==2020.7.14
    - requests-oauthlib==1.3.0
    - s3transfer==0.3.3
    - sacrebleu==1.4.13
    - sacremoses==0.0.43
    - scikit-image==0.17.2
    - scikit-learn==0.23.1
    - scipy==1.5.2
    - seaborn==0.11.0
    - sentencepiece==0.1.91
    - setuptools==50.3.0
    - shapely==1.7.0
    - sklearn==0.0
    - smart-open==2.1.1
    - soupsieve==2.0.1
    - spacy==2.3.2
    - sqlalchemy==1.3.18
    - srsly==1.0.2
    - tabulate==0.8.7
    - termcolor==1.1.0
    - tesserocr==2.5.1
    - thinc==7.4.1
    - threadpoolctl==2.1.0
    - thundersvm==0.3.12
    - thundersvm-cuda10-1==0.3.4
    - tifffile==2020.7.24
    - tokenizers==0.10.1
    - toml==0.10.1
    - tqdm==4.56.2
    - traitlets==4.3.3
    - transformers==4.3.2
    - typed-ast==1.4.1
    - ujson==3.0.0
    - urllib3==1.25.10
    - wasabi==0.7.1
    - wcwidth==0.2.5
    - wheel==0.35.1
    - wrapt==1.12.1
    - xgboost==1.1.1
    - yacs==0.1.7
    - zipp==3.1.0
prefix: /home/gullal/anaconda3/envs/mul_sent
